AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "coverage/**/*"
    - "vendor/**/*"
    - "*.gemspec"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/AbcSize:
  Max: 25

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/ClassLength:
  Max: 200
